### ISSUE TITLE
To be able to save in different computers

### ISSUE THREAD

**Issue by Stro21** [Stro21/Save_Image#1]
With the current code the png file that is it saved it can only work in just a computer, right now it just work in my PC but not in my laptop or in Pablo Straub's laptop.

**Comment by Stro21** [comment]
Now works in my PC and notebook.

**Comment by Stro21** [comment]
I need to test the program in my notebook.

**Comment by Stro21** [comment]
I test the program in my laptop and it works. Well now we need to make this program works in Pablo's laptop but for that Pablo must install Netbeans in his computer.

**Comment by PabloStraub** [comment]
No need to run in my computer for now. If needed in the future we open a new issue.
