### ISSUE TITLE
Formatting centers and filenames

### ISSUE THREAD

**Issue by PabloStraub** [Stro21/Save_Image#2]
La función de center.java

    @Override
    public String toString(){
        return "center=" + Double.toString(this.lat) + "," + Double.toString(this.lng);
    }

Podría reescribirse así:

    @Override
    public String toString(){
        return (this.lat < 0 ? "W" : "E") + Double.toString(Math.abs(this.lat)) + 
                   (this.lng < 0 ? "S" : "N") + Double.toString(Math.abs(this.lng));
    }

Una vez hecho esto, se puede eliminar la función para el nombre de archivo. Al momento de crear el archivo se haría algo así como (pseudocódigo, cambiar nombres de variables):

    nombreArchivo = (altaMontaña ? "m" : "v") + centro.toString();

**Comment by PabloStraub** [comment]
1) La función toString no puede modificarse porque se usa en el URL del llamado a Google Maps

2) El cuerpo de la propuesta de arriba se podría usar para el nombre del archivo.

3) En vez de 
`          Double.toString(Math.abs(this.lat))`
Conviene asegurarse que siempre use exactamente 5 decimales
`          String.format("%.5f", Math.abs(this.lat))`

**Comment by Stro21** [comment]
Bueno acabo de modificarlo pero me salio con formato con comas que puntos.

Esto se debe a que Java usa el formato de cada "locale", en este caso "ES/CL". Solución:

> `String.format(Locale.US,"%.5f", Math.abs(this.lat))`

**Comment by Stro21** [comment]
Bueno ahora el nombre del archivo esta listo. Incluso el mapa tiene su elevación.
