### ISSUE TITLE
Refactor Map code: fetch map image within class Map

### ISSUE THREAD

**Issue by PabloStraub** [Stro21/Save_Image#4]
Lines 40 to 50 in file Save_Image.java should become a new method Map.getImage, returning a byte array.

Then line 51 should become:

> `byte[] response = mapa.getImage();`

This implies that Map.getURL should become a private function.

**Comment by Stro21** [comment]
I complete this. Also I make a url a new attribute of the map class. Because of that I delete the function Map.getURL
