### ISSUE TITLE
Pathnames are weird

### ISSUE THREAD

**Issue by PabloStraub** [Stro21/Save_Image#5]
There is a pathname like

`"C:\\\\Users\\\\Eduardo Straub\\\\Documents\\\\NetBeansProjects\\\\Save_Image\\\\test\\\\images\\\\"`

This has too many backslashes.

The normal pathname `"C:\\Users\\eduar\\Documents\\NetBeansProjects\\Save_Image\\test\\images"` is repeated twice in the code.

**Comment by Stro21** [comment]
I change the path name.
