### ISSUE TITLE
Must iterate through different maps

### ISSUE THREAD

**Issue by PabloStraub** [Stro21/Save_Image#7]
After prior issues are resolved, a loop has to be implemented.

Variable center should be defined within the loop. Four new final variables should be created to define the looping:

> `final Center southWestArea, northEastArea;`
> `final Double stepLat, stepLng;`

The values for these will be defined with Pedro José as they determine the area of study.

Pseudocode for the loop is:

```
Center center = southWestArea;
while (center.getLat() < northEastArea.getLat()) {
    while (center.getLng() < northEastArea.getLng()) {
        // create a map at center
        // output map into a file
        center.setLng(center.getLng() + stepLng);
    }
    center.setLat(center.getLat() + stepLat);
    center.setLng(southWestArea.getLng());
}
```

**Comment by Stro21** [comment]
The program now iterate.
